version: "3.8"
services:
  backend:
    image: adview.cxview.ai/lpdev/dsd/dsd-backend-uat:latest
    environment:
      _JAVA_OPTIONS: "-Xms30m -Xmx1500m"
      SPRING_PROFILES_ACTIVE: "uat"
    volumes:
      - backend_logs:/app/logs
    networks:
      - dsd_internal
      - dsd_external

networks:
  dsd_internal:
  dsd_external:
    external: true

volumes:
  backend_logs: